version: "3"
services:
  pg-schema-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    command: -p 5432
    ports:
      - "5432:5432"
    volumes:
      - pg_schema_data:/var/lib/postgresql/data

volumes:
  pg_schema_data: {}
