name: TEST_FUNCTION

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:admin@localhost:5432/db
      run: make test
      continue-on-error: true

    - name: Upload report.json to Gist
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GIST_TOKEN}}
        script: |
          const fs = require('fs');
          const gistId = '070e58d1fbee37dab44796ed36c141bc';
          const fileName = './report.json';
          const fileContent = fs.readFileSync(fileName, {encoding: 'utf8'});
          
          await github.rest.gists.update({
            gist_id: gistId,
            files: {
              "report.json": {
                content: fileContent
              }
            }
          });
